// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Eh5F5Pqc-_6bfuwGU6CWURSbp2H82Fc',
    appId: '1:505137396208:android:7e2a3c28bf9da5bce14535',
    messagingSenderId: '505137396208',
    projectId: 'pricepick-demo',
    storageBucket: 'pricepick-demo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPsSFMLF6zKPKMupd3L4Ygh6KcLFgkk78',
    appId: '1:505137396208:ios:4890cbe47293180ae14535',
    messagingSenderId: '505137396208',
    projectId: 'pricepick-demo',
    storageBucket: 'pricepick-demo.firebasestorage.app',
    iosClientId: '505137396208-p4fhtajvfhi850vbq2uv9nonaj9ivc13.apps.googleusercontent.com',
    iosBundleId: 'com.pricepick.pricepickFlutter',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCElUPJAitnMZxttVYjboV0j4s_qpErAgA',
    appId: '1:505137396208:web:cea9d208c7745854e14535',
    messagingSenderId: '505137396208',
    projectId: 'pricepick-demo',
    authDomain: 'pricepick-demo.firebaseapp.com',
    storageBucket: 'pricepick-demo.firebasestorage.app',
    measurementId: 'G-RCQXSGTHX6',
  );
}
